const FEATS = {
  2014: [
    { name: "Grappler", category: "General", prerequisite: "Strength 13 or higher" }
  ],
  2024: [
    { name: "Alert", category: "Origin" },
    { name: "Magic Initiate", category: "Origin" },
    { name: "Savage Attacker", category: "Origin" },
    { name: "Skilled", category: "Origin" },
    { name: "Ability Score Improvement", category: "General", prerequisite: "Level 4+" },
    { name: "Grappler", category: "General", prerequisite: "Level 4+, Strength or Dexterity 13+" },
    { name: "Archery", category: "Fighting Style", prerequisite: "Fighting Style feature" },
    { name: "Defense", category: "Fighting Style", prerequisite: "Fighting Style feature" },
    { name: "Great Weapon Fighting", category: "Fighting Style", prerequisite: "Fighting Style feature" },
    { name: "Two-Weapon Fighting", category: "Fighting Style", prerequisite: "Fighting Style feature" },
    { name: "Boon of Combat Prowess", category: "Epic Boon", prerequisite: "Level 19+" },
    { name: "Boon of Dimensional Travel", category: "Epic Boon", prerequisite: "Level 19+" },
    { name: "Boon of Fate", category: "Epic Boon", prerequisite: "Level 19+" },
    { name: "Boon of Irresistible Offense", category: "Epic Boon", prerequisite: "Level 19+" },
    { name: "Boon of the Night Spirit", category: "Epic Boon", prerequisite: "Level 19+" },
    { name: "Boon of Spell Recall", category: "Epic Boon", prerequisite: "Level 19+" },
    { name: "Boon of Truesight", category: "Epic Boon", prerequisite: "Level 19+" }
  ]
};

const CLASS_FEATURES = {
  2014: {
    Barbarian: [[1,"Rage"],[1,"Unarmored Defense"],[2,"Reckless Attack"],[2,"Danger Sense"],[3,"Primal Path"],[4,"Ability Score Improvement"],[5,"Extra Attack"],[5,"Fast Movement"],[7,"Feral Instinct"],[9,"Brutal Critical"],[11,"Relentless Rage"],[15,"Persistent Rage"],[18,"Indomitable Might"],[20,"Primal Champion"]],
    Bard: [[1,"Spellcasting"],[1,"Bardic Inspiration"],[2,"Jack of All Trades"],[2,"Song of Rest"],[3,"Bard College"],[3,"Expertise"],[5,"Font of Inspiration"],[6,"Countercharm"],[10,"Magical Secrets"],[20,"Superior Inspiration"]],
    Cleric: [[1,"Spellcasting"],[1,"Divine Domain"],[2,"Channel Divinity"],[2,"Turn Undead"],[5,"Destroy Undead"],[10,"Divine Intervention"],[20,"Divine Intervention Improvement"]],
    Druid: [[1,"Druidic"],[1,"Spellcasting"],[2,"Wild Shape"],[2,"Druid Circle"],[18,"Timeless Body"],[18,"Beast Spells"],[20,"Archdruid"]],
    Fighter: [[1,"Fighting Style"],[1,"Second Wind"],[2,"Action Surge"],[3,"Martial Archetype"],[5,"Extra Attack"],[9,"Indomitable"],[11,"Extra Attack (2)"],[17,"Action Surge (2)"],[20,"Extra Attack (3)"]],
    Monk: [[1,"Unarmored Defense"],[1,"Martial Arts"],[2,"Ki"],[2,"Unarmored Movement"],[3,"Monastic Tradition"],[3,"Deflect Missiles"],[4,"Slow Fall"],[5,"Extra Attack"],[5,"Stunning Strike"],[6,"Ki-Empowered Strikes"],[7,"Evasion"],[7,"Stillness of Mind"],[10,"Purity of Body"],[14,"Diamond Soul"],[15,"Timeless Body"],[18,"Empty Body"],[20,"Perfect Self"]],
    Paladin: [[1,"Divine Sense"],[1,"Lay on Hands"],[2,"Fighting Style"],[2,"Spellcasting"],[2,"Divine Smite"],[3,"Divine Health"],[3,"Sacred Oath"],[5,"Extra Attack"],[6,"Aura of Protection"],[10,"Aura of Courage"],[11,"Improved Divine Smite"],[14,"Cleansing Touch"]],
    Ranger: [[1,"Favored Enemy"],[1,"Natural Explorer"],[2,"Fighting Style"],[2,"Spellcasting"],[3,"Ranger Archetype"],[3,"Primeval Awareness"],[5,"Extra Attack"],[8,"Land's Stride"],[10,"Hide in Plain Sight"],[14,"Vanish"],[18,"Feral Senses"],[20,"Foe Slayer"]],
    Rogue: [[1,"Expertise"],[1,"Sneak Attack"],[1,"Thieves' Cant"],[2,"Cunning Action"],[3,"Roguish Archetype"],[5,"Uncanny Dodge"],[7,"Evasion"],[11,"Reliable Talent"],[14,"Blindsense"],[15,"Slippery Mind"],[18,"Elusive"],[20,"Stroke of Luck"]],
    Sorcerer: [[1,"Spellcasting"],[1,"Sorcerous Origin"],[2,"Font of Magic"],[3,"Metamagic"],[20,"Sorcerous Restoration"]],
    Warlock: [[1,"Otherworldly Patron"],[1,"Pact Magic"],[2,"Eldritch Invocations"],[3,"Pact Boon"],[11,"Mystic Arcanum (6th)"],[13,"Mystic Arcanum (7th)"],[15,"Mystic Arcanum (8th)"],[17,"Mystic Arcanum (9th)"],[20,"Eldritch Master"]],
    Wizard: [[1,"Spellcasting"],[1,"Arcane Recovery"],[2,"Arcane Tradition"],[18,"Spell Mastery"],[20,"Signature Spells"]]
  },
  2024: {
    Barbarian: [[1,"Rage"],[1,"Unarmored Defense"],[1,"Weapon Mastery"],[2,"Danger Sense"],[2,"Reckless Attack"],[3,"Barbarian Subclass"],[3,"Primal Knowledge"],[5,"Extra Attack"],[5,"Fast Movement"],[7,"Feral Instinct"],[7,"Instinctive Pounce"],[9,"Brutal Strike"],[11,"Relentless Rage"],[15,"Persistent Rage"],[18,"Indomitable Might"],[20,"Primal Champion"]],
    Bard: [[1,"Bardic Inspiration"],[1,"Spellcasting"],[2,"Expertise"],[2,"Jack of All Trades"],[3,"Bard Subclass"],[5,"Font of Inspiration"],[7,"Countercharm"],[10,"Magical Secrets"],[18,"Superior Inspiration"],[20,"Words of Creation"]],
    Cleric: [[1,"Divine Order"],[1,"Spellcasting"],[2,"Channel Divinity"],[2,"Divine Spark"],[2,"Turn Undead"],[3,"Cleric Subclass"],[5,"Sear Undead"],[7,"Blessed Strikes"],[10,"Divine Intervention"],[14,"Improved Blessed Strikes"],[20,"Greater Divine Intervention"]],
    Druid: [[1,"Druidic"],[1,"Primal Order"],[1,"Spellcasting"],[2,"Wild Shape"],[2,"Wild Companion"],[3,"Druid Subclass"],[5,"Wild Resurgence"],[7,"Elemental Fury"],[15,"Improved Elemental Fury"],[18,"Beast Spells"],[20,"Archdruid"]],
    Fighter: [[1,"Fighting Style"],[1,"Second Wind"],[1,"Weapon Mastery"],[2,"Action Surge"],[2,"Tactical Mind"],[3,"Fighter Subclass"],[5,"Extra Attack"],[5,"Tactical Shift"],[9,"Indomitable"],[9,"Tactical Master"],[11,"Two Extra Attacks"],[13,"Studied Attacks"],[19,"Epic Boon"],[20,"Three Extra Attacks"]],
    Monk: [[1,"Martial Arts"],[1,"Unarmored Defense"],[2,"Monk's Focus"],[2,"Unarmored Movement"],[2,"Uncanny Metabolism"],[3,"Deflect Attacks"],[3,"Monk Subclass"],[4,"Slow Fall"],[5,"Extra Attack"],[5,"Stunning Strike"],[6,"Empowered Strikes"],[7,"Evasion"],[10,"Heightened Focus"],[13,"Deflect Energy"],[14,"Disciplined Survivor"],[15,"Perfect Focus"],[18,"Superior Defense"],[20,"Body and Mind"]],
    Paladin: [[1,"Lay on Hands"],[1,"Spellcasting"],[1,"Weapon Mastery"],[2,"Fighting Style"],[2,"Paladin's Smite"],[3,"Channel Divinity"],[3,"Paladin Subclass"],[5,"Extra Attack"],[5,"Faithful Steed"],[6,"Aura of Protection"],[9,"Abjure Foes"],[10,"Aura of Courage"],[11,"Radiant Strikes"],[14,"Restoring Touch"],[18,"Aura Expansion"]],
    Ranger: [[1,"Favored Enemy"],[1,"Spellcasting"],[1,"Weapon Mastery"],[2,"Deft Explorer"],[2,"Fighting Style"],[3,"Ranger Subclass"],[5,"Extra Attack"],[6,"Roving"],[9,"Expertise"],[10,"Tireless"],[13,"Relentless Hunter"],[14,"Nature's Veil"],[17,"Precise Hunter"],[18,"Feral Senses"],[20,"Foe Slayer"]],
    Rogue: [[1,"Expertise"],[1,"Sneak Attack"],[1,"Thieves' Cant"],[1,"Weapon Mastery"],[2,"Cunning Action"],[3,"Rogue Subclass"],[3,"Steady Aim"],[5,"Cunning Strike"],[5,"Uncanny Dodge"],[7,"Evasion"],[7,"Reliable Talent"],[11,"Improved Cunning Strike"],[14,"Devious Strikes"],[15,"Slippery Mind"],[18,"Elusive"],[20,"Stroke of Luck"]],
    Sorcerer: [[1,"Innate Sorcery"],[1,"Spellcasting"],[2,"Font of Magic"],[2,"Metamagic"],[3,"Sorcerer Subclass"],[5,"Sorcerous Restoration"],[7,"Sorcery Incarnate"],[20,"Arcane Apotheosis"]],
    Warlock: [[1,"Eldritch Invocations"],[1,"Pact Magic"],[2,"Magical Cunning"],[3,"Warlock Subclass"],[9,"Contact Patron"],[11,"Mystic Arcanum (6th)"],[13,"Mystic Arcanum (7th)"],[15,"Mystic Arcanum (8th)"],[17,"Mystic Arcanum (9th)"],[20,"Eldritch Master"]],
    Wizard: [[1,"Ritual Adept"],[1,"Spellcasting"],[1,"Arcane Recovery"],[2,"Scholar"],[3,"Wizard Subclass"],[5,"Memorize Spell"],[18,"Spell Mastery"],[20,"Signature Spells"]]
  }
};

const SUBCLASS_FEATURES = {
  2014: {
    "Path of the Berserker": [[3,"Frenzy"],[6,"Mindless Rage"],[10,"Intimidating Presence"],[14,"Retaliation"]],
    "College of Lore": [[3,"Bonus Proficiencies"],[3,"Cutting Words"],[6,"Additional Magical Secrets"],[14,"Peerless Skill"]],
    "Life Domain": [[1,"Bonus Proficiency"],[1,"Disciple of Life"],[2,"Preserve Life"],[6,"Blessed Healer"],[8,"Divine Strike"],[17,"Supreme Healing"]],
    "Circle of the Land": [[2,"Bonus Cantrip"],[2,"Natural Recovery"],[3,"Circle Spells"],[6,"Land's Stride"],[10,"Nature's Ward"],[14,"Nature's Sanctuary"]],
    "Champion": [[3,"Improved Critical"],[7,"Remarkable Athlete"],[10,"Additional Fighting Style"],[15,"Superior Critical"],[18,"Survivor"]],
    "Way of the Open Hand": [[3,"Open Hand Technique"],[6,"Wholeness of Body"],[11,"Tranquility"],[17,"Quivering Palm"]],
    "Oath of Devotion": [[3,"Oath Spells"],[3,"Sacred Weapon"],[3,"Turn the Unholy"],[7,"Aura of Devotion"],[15,"Purity of Spirit"],[20,"Holy Nimbus"]],
    "Hunter": [[3,"Hunter's Prey"],[7,"Defensive Tactics"],[11,"Multiattack"],[15,"Superior Hunter's Defense"]],
    "Thief": [[3,"Fast Hands"],[3,"Second-Story Work"],[9,"Supreme Sneak"],[13,"Use Magic Device"],[17,"Thief's Reflexes"]],
    "Draconic Bloodline": [[1,"Dragon Ancestor"],[1,"Draconic Resilience"],[6,"Elemental Affinity"],[14,"Dragon Wings"],[18,"Draconic Presence"]],
    "The Fiend": [[1,"Dark One's Blessing"],[6,"Dark One's Own Luck"],[10,"Fiendish Resilience"],[14,"Hurl Through Hell"]],
    "School of Evocation": [[2,"Evocation Savant"],[2,"Sculpt Spells"],[6,"Potent Cantrip"],[10,"Empowered Evocation"],[14,"Overchannel"]]
  },
  2024: {
    "Path of the Berserker": [[3,"Frenzy"],[6,"Mindless Rage"],[10,"Retaliation"],[14,"Intimidating Presence"]],
    "College of Lore": [[3,"Bonus Proficiencies"],[3,"Cutting Words"],[6,"Magical Discoveries"],[14,"Peerless Skill"]],
    "Life Domain": [[3,"Disciple of Life"],[3,"Preserve Life"],[6,"Blessed Healer"],[17,"Supreme Healing"]],
    "Circle of the Land": [[3,"Circle Spells"],[3,"Land's Aid"],[6,"Natural Recovery"],[10,"Nature's Ward"],[14,"Nature's Sanctuary"]],
    "Champion": [[3,"Improved Critical"],[3,"Remarkable Athlete"],[7,"Additional Fighting Style"],[10,"Heroic Warrior"],[15,"Superior Critical"],[18,"Survivor"]],
    "Warrior of the Open Hand": [[3,"Open Hand Technique"],[6,"Wholeness of Body"],[11,"Fleet Step"],[17,"Quivering Palm"]],
    "Oath of Devotion": [[3,"Oath Spells"],[3,"Sacred Weapon"],[7,"Aura of Devotion"],[15,"Smite of Protection"],[20,"Holy Nimbus"]],
    "Hunter": [[3,"Hunter's Lore"],[3,"Hunter's Prey"],[7,"Defensive Tactics"],[11,"Superior Hunter's Prey"],[15,"Superior Hunter's Defense"]],
    "Thief": [[3,"Fast Hands"],[3,"Second-Story Work"],[9,"Supreme Sneak"],[13,"Use Magic Device"],[17,"Thief's Reflexes"]],
    "Draconic Sorcery": [[3,"Draconic Resilience"],[3,"Draconic Spells"],[6,"Elemental Affinity"],[14,"Dragon Wings"],[18,"Dragon Companion"]],
    "Fiend Patron": [[3,"Dark One's Blessing"],[3,"Fiend Spells"],[6,"Dark One's Own Luck"],[10,"Fiendish Resilience"],[14,"Hurl Through Hell"]],
    "Evoker": [[3,"Evocation Savant"],[3,"Potent Cantrip"],[6,"Sculpt Spells"],[10,"Empowered Evocation"],[14,"Overchannel"]]
  }
};

const PROGRESSION_OPTIONS = {
  fightingStyles: {
    2014: ["Archery", "Defense", "Dueling", "Great Weapon Fighting", "Protection", "Two-Weapon Fighting"],
    2024: ["Archery", "Defense", "Great Weapon Fighting", "Two-Weapon Fighting"]
  },
  metamagic: {
    2014: ["Careful Spell", "Distant Spell", "Empowered Spell", "Extended Spell", "Heightened Spell", "Quickened Spell", "Subtle Spell", "Twinned Spell"],
    2024: ["Careful Spell", "Distant Spell", "Empowered Spell", "Extended Spell", "Heightened Spell", "Quickened Spell", "Seeking Spell", "Subtle Spell", "Transmuted Spell", "Twinned Spell"]
  },
  pactBoons2014: ["Pact of the Chain", "Pact of the Blade", "Pact of the Tome"],
  pactBoons2024: ["Pact of the Blade", "Pact of the Chain", "Pact of the Tome"],
  invocations: {
    2014: [
      "Agonizing Blast", "Armor of Shadows", "Ascendant Step", "Beast Speech", "Beguiling Influence",
      "Bewitching Whispers", "Book of Ancient Secrets", "Chains of Carceri", "Devil's Sight", "Dreadful Word",
      "Eldritch Sight", "Eldritch Spear", "Eyes of the Rune Keeper", "Fiendish Vigor", "Gaze of Two Minds",
      "Lifedrinker", "Mask of Many Faces", "Master of Myriad Forms", "Minions of Chaos", "Mire the Mind",
      "Misty Visions", "One with Shadows", "Otherworldly Leap", "Repelling Blast", "Sculptor of Flesh",
      "Sign of Ill Omen", "Thief of Five Fates", "Thirsting Blade", "Visions of Distant Realms",
      "Voice of the Chain Master", "Whispers of the Grave", "Witch Sight"
    ],
    2024: [
      "Agonizing Blast", "Armor of Shadows", "Ascendant Step", "Devil's Sight", "Devouring Blade",
      "Eldritch Mind", "Eldritch Smite", "Eldritch Spear", "Fiendish Vigor", "Gaze of Two Minds",
      "Gift of the Depths", "Gift of the Protectors", "Investment of the Chain Master", "Lessons of the First Ones",
      "Lifedrinker", "Mask of Many Faces", "Master of Myriad Forms", "Misty Visions", "One with Shadows",
      "Otherworldly Leap", "Pact of the Blade", "Pact of the Chain", "Pact of the Tome", "Repelling Blast",
      "Thirsting Blade", "Visions of Distant Realms", "Whispers of the Grave", "Witch Sight"
    ]
  },
  weapons: [
    "Battleaxe", "Blowgun", "Club", "Dagger", "Dart", "Flail", "Glaive", "Greataxe", "Greatclub",
    "Greatsword", "Halberd", "Hand Crossbow", "Handaxe", "Heavy Crossbow", "Javelin", "Lance",
    "Light Crossbow", "Light Hammer", "Longbow", "Longsword", "Mace", "Maul", "Morningstar",
    "Musket", "Pike", "Pistol", "Quarterstaff", "Rapier", "Scimitar", "Shortbow", "Shortsword",
    "Sickle", "Sling", "Spear", "Trident", "War Pick", "Warhammer", "Whip"
  ],
  skills: ["Acrobatics", "Animal Handling", "Arcana", "Athletics", "Deception", "History", "Insight", "Intimidation", "Investigation", "Medicine", "Nature", "Perception", "Performance", "Persuasion", "Religion", "Sleight of Hand", "Stealth", "Survival"]
};

const WEAPON_MASTERY_PROPERTIES = {
  Battleaxe: "Topple", Blowgun: "Vex", Club: "Slow", Dagger: "Nick", Dart: "Vex", Flail: "Sap",
  Glaive: "Graze", Greataxe: "Cleave", Greatclub: "Push", Greatsword: "Graze", Halberd: "Cleave",
  "Hand Crossbow": "Vex", Handaxe: "Vex", "Heavy Crossbow": "Push", Javelin: "Slow", Lance: "Topple",
  "Light Crossbow": "Slow", "Light Hammer": "Nick", Longbow: "Slow", Longsword: "Sap", Mace: "Sap",
  Maul: "Topple", Morningstar: "Sap", Musket: "Slow", Pike: "Push", Pistol: "Vex",
  Quarterstaff: "Topple", Rapier: "Vex", Scimitar: "Nick", Shortbow: "Vex", Shortsword: "Vex",
  Sickle: "Nick", Sling: "Slow", Spear: "Sap", Trident: "Topple", "War Pick": "Sap",
  Warhammer: "Push", Whip: "Slow"
};

const FULL_CASTER_SLOTS = [
  [2], [3], [4,2], [4,3], [4,3,2], [4,3,3], [4,3,3,1], [4,3,3,2], [4,3,3,3,1],
  [4,3,3,3,2], [4,3,3,3,2,1], [4,3,3,3,2,1], [4,3,3,3,2,1,1],
  [4,3,3,3,2,1,1], [4,3,3,3,2,1,1,1], [4,3,3,3,2,1,1,1],
  [4,3,3,3,2,1,1,1,1], [4,3,3,3,3,1,1,1,1], [4,3,3,3,3,2,1,1,1],
  [4,3,3,3,3,2,2,1,1]
];

const HALF_CASTER_SLOTS_2014 = [
  [], [2], [3], [3], [4,2], [4,2], [4,3], [4,3], [4,3,2], [4,3,2],
  [4,3,3], [4,3,3], [4,3,3,1], [4,3,3,1], [4,3,3,2], [4,3,3,2],
  [4,3,3,3,1], [4,3,3,3,1], [4,3,3,3,2], [4,3,3,3,2]
];

const HALF_CASTER_SLOTS_2024 = [
  [2], [2], [3], [3], [4,2], [4,2], [4,3], [4,3], [4,3,2], [4,3,2],
  [4,3,3], [4,3,3], [4,3,3,1], [4,3,3,1], [4,3,3,2], [4,3,3,2],
  [4,3,3,3,1], [4,3,3,3,1], [4,3,3,3,2], [4,3,3,3,2]
];

const THIRD_CASTER_SLOTS = [
  [], [], [2], [3], [3], [3], [4,2], [4,2], [4,2], [4,3],
  [4,3], [4,3], [4,3,2], [4,3,2], [4,3,2], [4,3,3],
  [4,3,3], [4,3,3], [4,3,3,1], [4,3,3,1]
];

const equipmentItem = (name, type, cost, weight, details = "") => ({ name, type, cost, weight, details });
const RARITY_ORDER = ["Common", "Uncommon", "Rare", "Very Rare", "Legendary", "Artifact"];
const magicItem = (name, category, rarity, attune, effect, weight = 1) => ({
  name,
  type: category,
  cost: "—",
  weight,
  rarity,
  attunement: attune || "",
  details: `${rarity}${attune ? ` · Requires attunement${typeof attune === "string" ? ` ${attune}` : ""}` : ""} · ${effect}`
});
const EQUIPMENT_CATALOG = [
  equipmentItem("Club", "Simple Melee Weapon", "1 SP", 2, "1d4 bludgeoning · Light · Slow mastery"),
  equipmentItem("Dagger", "Simple Melee Weapon", "2 GP", 1, "1d4 piercing · Finesse, light, thrown · Nick mastery"),
  equipmentItem("Greatclub", "Simple Melee Weapon", "2 SP", 10, "1d8 bludgeoning · Two-handed · Push mastery"),
  equipmentItem("Handaxe", "Simple Melee Weapon", "5 GP", 2, "1d6 slashing · Light, thrown · Vex mastery"),
  equipmentItem("Javelin", "Simple Melee Weapon", "5 SP", 2, "1d6 piercing · Thrown · Slow mastery"),
  equipmentItem("Light Hammer", "Simple Melee Weapon", "2 GP", 2, "1d4 bludgeoning · Light, thrown · Nick mastery"),
  equipmentItem("Mace", "Simple Melee Weapon", "5 GP", 4, "1d6 bludgeoning · Sap mastery"),
  equipmentItem("Quarterstaff", "Simple Melee Weapon", "2 SP", 4, "1d6 bludgeoning · Versatile (1d8) · Topple mastery"),
  equipmentItem("Sickle", "Simple Melee Weapon", "1 GP", 2, "1d4 slashing · Light · Nick mastery"),
  equipmentItem("Spear", "Simple Melee Weapon", "1 GP", 3, "1d6 piercing · Thrown, versatile (1d8) · Sap mastery"),
  equipmentItem("Dart", "Simple Ranged Weapon", "5 CP", 0.25, "1d4 piercing · Finesse, thrown · Vex mastery"),
  equipmentItem("Light Crossbow", "Simple Ranged Weapon", "25 GP", 5, "1d8 piercing · Ammunition, loading, two-handed · Slow mastery"),
  equipmentItem("Shortbow", "Simple Ranged Weapon", "25 GP", 2, "1d6 piercing · Ammunition, two-handed · Vex mastery"),
  equipmentItem("Sling", "Simple Ranged Weapon", "1 SP", 0, "1d4 bludgeoning · Ammunition · Slow mastery"),
  equipmentItem("Battleaxe", "Martial Melee Weapon", "10 GP", 4, "1d8 slashing · Versatile (1d10) · Topple mastery"),
  equipmentItem("Flail", "Martial Melee Weapon", "10 GP", 2, "1d8 bludgeoning · Sap mastery"),
  equipmentItem("Glaive", "Martial Melee Weapon", "20 GP", 6, "1d10 slashing · Heavy, reach, two-handed · Graze mastery"),
  equipmentItem("Greataxe", "Martial Melee Weapon", "30 GP", 7, "1d12 slashing · Heavy, two-handed · Cleave mastery"),
  equipmentItem("Greatsword", "Martial Melee Weapon", "50 GP", 6, "2d6 slashing · Heavy, two-handed · Graze mastery"),
  equipmentItem("Halberd", "Martial Melee Weapon", "20 GP", 6, "1d10 slashing · Heavy, reach, two-handed · Cleave mastery"),
  equipmentItem("Lance", "Martial Melee Weapon", "10 GP", 6, "1d10 piercing · Heavy, reach, two-handed while unmounted · Topple mastery"),
  equipmentItem("Longsword", "Martial Melee Weapon", "15 GP", 3, "1d8 slashing · Versatile (1d10) · Sap mastery"),
  equipmentItem("Maul", "Martial Melee Weapon", "10 GP", 10, "2d6 bludgeoning · Heavy, two-handed · Topple mastery"),
  equipmentItem("Morningstar", "Martial Melee Weapon", "15 GP", 4, "1d8 piercing · Sap mastery"),
  equipmentItem("Pike", "Martial Melee Weapon", "5 GP", 18, "1d10 piercing · Heavy, reach, two-handed · Push mastery"),
  equipmentItem("Rapier", "Martial Melee Weapon", "25 GP", 2, "1d8 piercing · Finesse · Vex mastery"),
  equipmentItem("Scimitar", "Martial Melee Weapon", "25 GP", 3, "1d6 slashing · Finesse, light · Nick mastery"),
  equipmentItem("Shortsword", "Martial Melee Weapon", "10 GP", 2, "1d6 piercing · Finesse, light · Vex mastery"),
  equipmentItem("Trident", "Martial Melee Weapon", "5 GP", 4, "1d8 piercing · Thrown, versatile (1d10) · Topple mastery"),
  equipmentItem("War Pick", "Martial Melee Weapon", "5 GP", 2, "1d8 piercing · Versatile (1d10) · Sap mastery"),
  equipmentItem("Warhammer", "Martial Melee Weapon", "15 GP", 5, "1d8 bludgeoning · Versatile (1d10) · Push mastery"),
  equipmentItem("Whip", "Martial Melee Weapon", "2 GP", 3, "1d4 slashing · Finesse, reach · Slow mastery"),
  equipmentItem("Blowgun", "Martial Ranged Weapon", "10 GP", 1, "1 piercing · Ammunition, loading · Vex mastery"),
  equipmentItem("Hand Crossbow", "Martial Ranged Weapon", "75 GP", 3, "1d6 piercing · Ammunition, light, loading · Vex mastery"),
  equipmentItem("Heavy Crossbow", "Martial Ranged Weapon", "50 GP", 18, "1d10 piercing · Ammunition, heavy, loading, two-handed · Push mastery"),
  equipmentItem("Longbow", "Martial Ranged Weapon", "50 GP", 2, "1d8 piercing · Ammunition, heavy, two-handed · Slow mastery"),
  equipmentItem("Pistol", "Martial Ranged Weapon", "250 GP", 3, "1d10 piercing · Ammunition, loading · Vex mastery"),
  equipmentItem("Musket", "Martial Ranged Weapon", "500 GP", 10, "1d12 piercing · Ammunition, loading, two-handed · Slow mastery"),
  // ── Firearms (renaissance) ──
  equipmentItem("Palm Pistol", "Martial Ranged Weapon", "150 GP", 1, "1d8 piercing · Firearm · Ammunition (range 15/45), loading · easily concealed"),
  equipmentItem("Pepperbox", "Martial Ranged Weapon", "250 GP", 4, "1d10 piercing · Firearm · Ammunition (range 40/120), reload 6 shots"),
  equipmentItem("Blunderbuss", "Martial Ranged Weapon", "300 GP", 5, "2d6 piercing · Firearm · Ammunition (range 15/60), loading, two-handed"),
  equipmentItem("Bad News", "Martial Ranged Weapon", "800 GP", 20, "2d12 piercing · Firearm · Ammunition (range 200/800), loading, two-handed · a heavy long-range rifle"),
  // ── Firearms (modern) ──
  equipmentItem("Semi-Automatic Pistol", "Martial Ranged Weapon", "—", 3, "2d6 piercing · Firearm · Ammunition (range 30/90), reload 15 shots"),
  equipmentItem("Revolver", "Martial Ranged Weapon", "—", 3, "2d8 piercing · Firearm · Ammunition (range 40/120), reload 6 shots"),
  equipmentItem("Hunting Rifle", "Martial Ranged Weapon", "—", 8, "2d10 piercing · Firearm · Ammunition (range 80/240), reload 5 shots, two-handed"),
  equipmentItem("Automatic Rifle", "Martial Ranged Weapon", "—", 8, "2d8 piercing · Firearm · Ammunition (range 80/240), reload 30 shots, burst fire, two-handed"),
  equipmentItem("Shotgun", "Martial Ranged Weapon", "—", 7, "2d8 piercing · Firearm · Ammunition (range 30/90), reload 2 shots, two-handed"),
  equipmentItem("Automatic Shotgun", "Martial Ranged Weapon", "—", 8, "2d8 piercing · Firearm · Ammunition (range 30/90), reload 10 shots, burst fire, two-handed"),
  // ── Firearms (futuristic) ──
  equipmentItem("Laser Pistol", "Martial Ranged Weapon", "—", 2, "3d6 radiant · Firearm · Ammunition (range 40/120), reload 50 charges"),
  equipmentItem("Laser Rifle", "Martial Ranged Weapon", "—", 7, "3d8 radiant · Firearm · Ammunition (range 100/300), reload 30 charges, two-handed"),
  equipmentItem("Antimatter Rifle", "Martial Ranged Weapon", "—", 10, "6d8 necrotic · Firearm · Ammunition (range 120/360), reload 2 shots, two-handed"),
  // ── Firearm ammunition ──
  equipmentItem("Bullets, Firearm (10)", "Ammunition", "3 GP", 2, "Powder and shot for renaissance firearms such as pistols and muskets"),
  equipmentItem("Bullets, Modern (10)", "Ammunition", "9 GP", 1, "Metal cartridges for modern firearms"),
  equipmentItem("Energy Cell", "Ammunition", "—", 5, "Rechargeable power cell that feeds laser and antimatter weapons"),
  equipmentItem("Padded Armor", "Light Armor", "5 GP", 8, "AC 11 + Dexterity modifier · Stealth disadvantage"),
  equipmentItem("Leather Armor", "Light Armor", "10 GP", 10, "AC 11 + Dexterity modifier"),
  equipmentItem("Studded Leather Armor", "Light Armor", "45 GP", 13, "AC 12 + Dexterity modifier"),
  equipmentItem("Hide Armor", "Medium Armor", "10 GP", 12, "AC 12 + Dexterity modifier (maximum +2)"),
  equipmentItem("Chain Shirt", "Medium Armor", "50 GP", 20, "AC 13 + Dexterity modifier (maximum +2)"),
  equipmentItem("Scale Mail", "Medium Armor", "50 GP", 45, "AC 14 + Dexterity modifier (maximum +2) · Stealth disadvantage"),
  equipmentItem("Breastplate", "Medium Armor", "400 GP", 20, "AC 14 + Dexterity modifier (maximum +2)"),
  equipmentItem("Half Plate Armor", "Medium Armor", "750 GP", 40, "AC 15 + Dexterity modifier (maximum +2) · Stealth disadvantage"),
  equipmentItem("Ring Mail", "Heavy Armor", "30 GP", 40, "AC 14 · Stealth disadvantage"),
  equipmentItem("Chain Mail", "Heavy Armor", "75 GP", 55, "AC 16 · Strength 13 · Stealth disadvantage"),
  equipmentItem("Splint Armor", "Heavy Armor", "200 GP", 60, "AC 17 · Strength 15 · Stealth disadvantage"),
  equipmentItem("Plate Armor", "Heavy Armor", "1,500 GP", 65, "AC 18 · Strength 15 · Stealth disadvantage"),
  equipmentItem("Shield", "Shield", "10 GP", 6, "+2 Armor Class while wielded"),
  equipmentItem("Backpack", "Adventuring Gear", "2 GP", 5, "Holds gear and supplies"),
  equipmentItem("Bedroll", "Adventuring Gear", "1 GP", 7, "Portable sleeping gear"),
  equipmentItem("Blanket", "Adventuring Gear", "5 SP", 3, "Travel blanket"),
  equipmentItem("Book", "Adventuring Gear", "25 GP", 5, "A written volume"),
  equipmentItem("Caltrops", "Adventuring Gear", "1 GP", 2, "Bag of twenty caltrops"),
  equipmentItem("Candle", "Adventuring Gear", "1 CP", 0, "Provides dim light"),
  equipmentItem("Case, Map or Scroll", "Adventuring Gear", "1 GP", 1, "Protective document case"),
  equipmentItem("Chain, 10 feet", "Adventuring Gear", "5 GP", 10, "Ten feet of chain"),
  equipmentItem("Crowbar", "Adventuring Gear", "2 GP", 5, "Provides leverage when appropriate"),
  equipmentItem("Flask or Tankard", "Adventuring Gear", "2 CP", 1, "Liquid container"),
  equipmentItem("Grappling Hook", "Adventuring Gear", "2 GP", 4, "Climbing and securing gear"),
  equipmentItem("Healer's Kit", "Adventuring Gear", "5 GP", 3, "Ten uses for stabilizing creatures"),
  equipmentItem("Holy Water", "Adventuring Gear", "25 GP", 1, "A flask of consecrated water"),
  equipmentItem("Lantern, Hooded", "Adventuring Gear", "5 GP", 2, "Directional light source"),
  equipmentItem("Lock", "Adventuring Gear", "10 GP", 1, "A key-operated lock"),
  equipmentItem("Manacles", "Adventuring Gear", "2 GP", 6, "Metal restraints"),
  equipmentItem("Mess Kit", "Adventuring Gear", "2 SP", 1, "Portable eating and cooking kit"),
  equipmentItem("Oil, Flask", "Adventuring Gear", "1 SP", 1, "Fuel or improvised combustible"),
  equipmentItem("Potion of Healing", "Potion", "50 GP", 0.5, "Consumable healing potion"),
  equipmentItem("Rations, 1 day", "Adventuring Gear", "5 SP", 2, "One day of preserved food"),
  equipmentItem("Rope, Hempen, 50 feet", "Adventuring Gear", "1 GP", 10, "Fifty feet of hempen rope"),
  equipmentItem("Rope, Silk, 50 feet", "Adventuring Gear", "10 GP", 5, "Fifty feet of silk rope"),
  equipmentItem("Spellbook", "Adventuring Gear", "50 GP", 3, "A wizard's spellbook"),
  equipmentItem("Tinderbox", "Adventuring Gear", "5 SP", 1, "Used to start a fire"),
  equipmentItem("Torch", "Adventuring Gear", "1 CP", 1, "Provides bright and dim light"),
  equipmentItem("Waterskin", "Adventuring Gear", "2 SP", 5, "Liquid container; weight shown when full"),
  equipmentItem("Thieves' Tools", "Tool", "25 GP", 1, "Tools for locks and traps"),
  equipmentItem("Herbalism Kit", "Tool", "5 GP", 3, "Tools for identifying and applying herbs"),
  equipmentItem("Disguise Kit", "Tool", "25 GP", 3, "Cosmetics and disguise supplies"),
  equipmentItem("Musical Instrument", "Tool", "Varies", 3, "Choose a specific instrument"),
  equipmentItem("Arcane Focus", "Spellcasting Focus", "Varies", 1, "Focus for arcane spells"),
  equipmentItem("Druidic Focus", "Spellcasting Focus", "Varies", 1, "Focus for druid spells"),
  equipmentItem("Holy Symbol", "Spellcasting Focus", "5 GP", 1, "Focus for divine spells"),
  // ── Magic Items ──────────────────────────────────────────────
  magicItem("Potion of Climbing", "Potion", "Common", false, "Gain a climbing speed equal to your walking speed for 1 hour, with advantage on checks to climb.", 0.5),
  magicItem("Potion of Greater Healing", "Potion", "Uncommon", false, "Regain 4d4 + 4 hit points when you drink it.", 0.5),
  magicItem("Potion of Superior Healing", "Potion", "Rare", false, "Regain 8d4 + 8 hit points when you drink it.", 0.5),
  magicItem("Potion of Supreme Healing", "Potion", "Very Rare", false, "Regain 10d4 + 20 hit points when you drink it.", 0.5),
  magicItem("Potion of Fire Breath", "Potion", "Uncommon", false, "Exhale fire as a bonus action, dealing area fire damage, up to three times within 1 hour.", 0.5),
  magicItem("Potion of Water Breathing", "Potion", "Uncommon", false, "Breathe underwater for 1 hour after drinking it.", 0.5),
  magicItem("Potion of Heroism", "Potion", "Rare", false, "Gain 10 temporary hit points and the benefit of the Bless spell for 1 hour.", 0.5),
  magicItem("Potion of Invisibility", "Potion", "Very Rare", false, "Become invisible for 1 hour or until you attack or cast a spell.", 0.5),
  magicItem("Potion of Flying", "Potion", "Very Rare", false, "Gain a flying speed equal to your walking speed for 1 hour.", 0.5),
  magicItem("Potion of Speed", "Potion", "Very Rare", false, "Gain the effect of the Haste spell for 1 minute, with no lethargy afterward.", 0.5),
  magicItem("Elixir of Health", "Potion", "Rare", false, "Cure several ailing conditions and remove all exhaustion when you drink it.", 0.5),
  magicItem("Oil of Sharpness", "Potion", "Very Rare", false, "Coat a weapon so it gains +3 to attack and damage for 1 hour.", 0.5),
  magicItem("Spell Scroll (Cantrip)", "Scroll", "Common", false, "Cast the inscribed cantrip once; the scroll then crumbles to dust.", 0),
  magicItem("Spell Scroll (1st Level)", "Scroll", "Common", false, "Cast the inscribed 1st-level spell once; the scroll then crumbles to dust.", 0),
  magicItem("Spell Scroll (3rd Level)", "Scroll", "Uncommon", false, "Cast the inscribed 3rd-level spell once; the scroll then crumbles to dust.", 0),
  magicItem("Spell Scroll (5th Level)", "Scroll", "Rare", false, "Cast the inscribed 5th-level spell once; the scroll then crumbles to dust.", 0),
  magicItem("Spell Scroll (9th Level)", "Scroll", "Very Rare", false, "Cast the inscribed 9th-level spell once; the scroll then crumbles to dust.", 0),
  magicItem("Driftglobe", "Wondrous Item", "Common", false, "A glass sphere that floats near you and sheds light on command.", 1),
  magicItem("Cloak of Billowing", "Wondrous Item", "Common", false, "As a bonus action, make the cloak billow dramatically on command.", 1),
  magicItem("Clockwork Amulet", "Wondrous Item", "Common", false, "Once per long rest, skip the attack roll and treat the d20 as a 10.", 1),
  magicItem("Enduring Spellbook", "Wondrous Item", "Common", false, "This book and its writing withstand fire, water, and the passage of time.", 3),
  magicItem("Boots of False Tracks", "Wondrous Item", "Common", false, "Leave tracks of another kind of humanoid of your choice.", 1),
  magicItem("Charlatan's Die", "Wondrous Item", "Common", true, "Roll this die and will it to land on any number you choose.", 0),
  magicItem("Bag of Holding", "Wondrous Item", "Uncommon", false, "An extradimensional pouch holding up to 500 lb. in a much smaller space.", 15),
  magicItem("Immovable Rod", "Rod", "Uncommon", false, "Press the button to fix the rod in place in midair, holding up to 8,000 lb.", 2),
  magicItem("Cloak of Elvenkind", "Wondrous Item", "Uncommon", true, "Advantage on Stealth checks to hide; others have disadvantage to spot you.", 1),
  magicItem("Boots of Elvenkind", "Wondrous Item", "Uncommon", false, "Your steps make no sound, granting advantage on Stealth checks to move quietly.", 1),
  magicItem("Boots of Striding and Springing", "Wondrous Item", "Uncommon", true, "Your walking speed becomes 30 feet and your jump distance is tripled.", 1),
  magicItem("Winged Boots", "Wondrous Item", "Uncommon", true, "Gain a flying speed equal to your walking speed for up to 4 hours per day.", 1),
  magicItem("Slippers of Spider Climbing", "Wondrous Item", "Uncommon", true, "Climb difficult surfaces, even ceilings, leaving your hands free.", 1),
  magicItem("Gauntlets of Ogre Power", "Wondrous Item", "Uncommon", true, "Your Strength score becomes 19 while you wear them.", 2),
  magicItem("Headband of Intellect", "Wondrous Item", "Uncommon", true, "Your Intelligence score becomes 19 while you wear it.", 1),
  magicItem("Bracers of Archery", "Wondrous Item", "Uncommon", true, "Proficiency with longbows and shortbows, and +2 damage with them.", 1),
  magicItem("Cloak of Protection", "Wondrous Item", "Uncommon", true, "+1 bonus to AC and all saving throws while worn.", 1),
  magicItem("Eyes of the Eagle", "Wondrous Item", "Uncommon", true, "Advantage on Perception checks that rely on sight.", 0),
  magicItem("Goggles of Night", "Wondrous Item", "Uncommon", false, "Gain darkvision out to 60 feet while worn.", 0),
  magicItem("Sentinel Shield", "Armor (shield)", "Uncommon", false, "Advantage on initiative and Perception checks while wielded.", 6),
  magicItem("Wand of Magic Missiles", "Wand", "Uncommon", false, "7 charges; expend charges to cast Magic Missile at higher levels.", 1),
  magicItem("Wand of the War Mage, +1", "Wand", "Uncommon", "by a spellcaster", "+1 to spell attack rolls and you ignore half cover with spell attacks.", 1),
  magicItem("Weapon, +1", "Weapon (any)", "Uncommon", false, "+1 bonus to attack and damage rolls made with this magic weapon.", 3),
  magicItem("Shield, +1", "Armor (shield)", "Uncommon", false, "An additional +1 bonus to AC beyond the shield's normal bonus.", 6),
  magicItem("Ring of Mind Shielding", "Ring", "Uncommon", true, "Immune to magic that reads your thoughts or detects your lies.", 0),
  magicItem("Ring of Jumping", "Ring", "Uncommon", true, "Cast Jump on yourself at will as a bonus action.", 0),
  magicItem("Bag of Tricks", "Wondrous Item", "Uncommon", false, "Draw a fuzzy ball that becomes a random beast to fight for you.", 0.5),
  magicItem("Pipes of Haunting", "Wondrous Item", "Uncommon", false, "Play a haunting tune to frighten creatures that can hear you.", 2),
  magicItem("Flame Tongue", "Weapon (any sword)", "Rare", true, "Speak the command word to wreathe the blade in fire for +2d6 fire damage and bright light.", 3),
  magicItem("Frost Brand", "Weapon (any sword)", "Very Rare", true, "+1d6 cold damage, resistance to fire, and the blade sheds light in cold places.", 3),
  magicItem("Dagger of Venom", "Weapon (dagger)", "Rare", false, "+1 dagger that can coat itself in deadly poison once per day.", 1),
  magicItem("Mace of Disruption", "Weapon (mace)", "Rare", true, "Extra radiant damage to fiends and undead, which may be frightened or destroyed.", 4),
  magicItem("Weapon, +2", "Weapon (any)", "Rare", false, "+2 bonus to attack and damage rolls made with this magic weapon.", 3),
  magicItem("Shield, +2", "Armor (shield)", "Rare", false, "An additional +2 bonus to AC beyond the shield's normal bonus.", 6),
  magicItem("Armor, +1", "Armor (any)", "Rare", false, "+1 bonus to AC while you wear this armor.", 20),
  magicItem("Amulet of Health", "Wondrous Item", "Rare", true, "Your Constitution score becomes 19 while you wear it.", 1),
  magicItem("Bracers of Defense", "Wondrous Item", "Rare", true, "+2 bonus to AC while wearing no armor and wielding no shield.", 1),
  magicItem("Wraps of Unarmed Prowess, +1", "Wondrous Item", "Uncommon", false, "Cloth wraps that make your unarmed strikes count as magical and add +1 to their attack and damage rolls.", 1),
  magicItem("Wraps of Unarmed Prowess, +2", "Wondrous Item", "Rare", false, "Cloth wraps that make your unarmed strikes count as magical and add +2 to their attack and damage rolls.", 1),
  magicItem("Wraps of Unarmed Prowess, +3", "Wondrous Item", "Very Rare", false, "Cloth wraps that make your unarmed strikes count as magical and add +3 to their attack and damage rolls.", 1),
  magicItem("Cloak of Displacement", "Wondrous Item", "Rare", true, "Attackers have disadvantage against you until you take damage.", 1),
  magicItem("Boots of Speed", "Wondrous Item", "Rare", true, "Click your heels to double your speed and impose disadvantage on opportunity attacks.", 1),
  magicItem("Boots of Levitation", "Wondrous Item", "Rare", true, "Cast Levitate on yourself at will.", 1),
  magicItem("Periapt of Wound Closure", "Wondrous Item", "Rare", true, "Stabilize automatically when dying and double the hit points you regain from Hit Dice.", 0),
  magicItem("Helm of Telepathy", "Wondrous Item", "Rare", true, "Read the surface thoughts of a creature and send it silent messages.", 3),
  magicItem("Gem of Seeing", "Wondrous Item", "Rare", true, "See through illusions and spot invisible creatures within 120 feet.", 1),
  magicItem("Cape of the Mountebank", "Wondrous Item", "Rare", false, "Cast Dimension Door once per day, leaving a puff of smoke behind.", 1),
  magicItem("Ring of Protection", "Ring", "Rare", true, "+1 bonus to AC and all saving throws.", 0),
  magicItem("Ring of Spell Storing", "Ring", "Rare", true, "Store up to 5 levels of spells within the ring to cast later.", 0),
  magicItem("Ring of Free Action", "Ring", "Rare", true, "Difficult terrain never slows you, and you can't be paralyzed or restrained by magic.", 0),
  magicItem("Ring of Resistance", "Ring", "Rare", true, "Resistance to one damage type determined by the ring's gem.", 0),
  magicItem("Wand of Fireballs", "Wand", "Rare", "by a spellcaster", "7 charges; expend charges to cast Fireball at higher levels.", 1),
  magicItem("Wand of Lightning Bolts", "Wand", "Rare", "by a spellcaster", "7 charges; expend charges to cast Lightning Bolt at higher levels.", 1),
  magicItem("Staff of Charming", "Staff", "Rare", "by a spellcaster", "Cast Charm Person, Command, or Comprehend Languages, and absorb enchantments.", 4),
  magicItem("Weapon, +3", "Weapon (any)", "Very Rare", false, "+3 bonus to attack and damage rolls made with this magic weapon.", 3),
  magicItem("Armor, +2", "Armor (any)", "Very Rare", false, "+2 bonus to AC while you wear this armor.", 20),
  magicItem("Shield, +3", "Armor (shield)", "Very Rare", false, "An additional +3 bonus to AC beyond the shield's normal bonus.", 6),
  magicItem("Dancing Sword", "Weapon (any sword)", "Very Rare", true, "Toss the blade into the air to have it fly and attack on its own for a short time.", 3),
  magicItem("Nine Lives Stealer", "Weapon (any sword)", "Very Rare", true, "+2 sword that can slay a badly wounded creature outright on a critical hit.", 3),
  magicItem("Oathbow", "Weapon (longbow)", "Very Rare", true, "Name a sworn enemy to gain bonus damage and accuracy against it.", 2),
  magicItem("Staff of Fire", "Staff", "Very Rare", "by a spellcaster", "Cast Burning Hands, Fireball, and Wall of Fire, and gain resistance to fire.", 4),
  magicItem("Staff of Power", "Staff", "Very Rare", "by a spellcaster", "+2 to weapon and spell attacks, +2 AC and saves, and several potent spells.", 4),
  magicItem("Rod of Absorption", "Rod", "Very Rare", true, "Absorb a spell targeting you and store its energy to power your own spells.", 2),
  magicItem("Wand of Polymorph", "Wand", "Very Rare", true, "7 charges; expend a charge to cast Polymorph.", 1),
  magicItem("Ring of Regeneration", "Ring", "Very Rare", true, "Regain hit points over time and regrow severed limbs.", 0),
  magicItem("Ring of Telekinesis", "Ring", "Very Rare", true, "Cast Telekinesis at will against objects and creatures.", 0),
  magicItem("Cloak of Arachnida", "Wondrous Item", "Very Rare", true, "Spider climb, resistance to poison, immunity to webs, and cast Web.", 1),
  magicItem("Manual of Bodily Health", "Wondrous Item", "Very Rare", false, "Study for 48 hours to permanently raise your Constitution by 2.", 5),
  magicItem("Tome of Clear Thought", "Wondrous Item", "Very Rare", false, "Study for 48 hours to permanently raise your Intelligence by 2.", 5),
  magicItem("Horn of Valhalla (Bronze)", "Wondrous Item", "Very Rare", false, "Sound the horn to summon spectral warriors to fight for you.", 2),
  magicItem("Vorpal Sword", "Weapon (any slashing sword)", "Legendary", true, "Ignore slashing resistance and, on a natural 20, sever a creature's head.", 3),
  magicItem("Holy Avenger", "Weapon (any sword)", "Legendary", "by a paladin", "+3 sword that deals extra radiant damage to fiends and undead and projects a protective aura.", 3),
  magicItem("Defender", "Weapon (any sword)", "Legendary", true, "+3 sword; each turn you may shift some of its bonus from attack to your AC.", 3),
  magicItem("Luck Blade", "Weapon (any sword)", "Legendary", true, "+1 sword granting a luck reroll each day and a small number of wishes.", 3),
  magicItem("Sword of Sharpness", "Weapon (any sword)", "Rare", true, "On a hard hit, deal extra slashing damage and possibly lop off a limb.", 3),
  magicItem("Belt of Storm Giant Strength", "Wondrous Item", "Legendary", true, "Your Strength score becomes 29 while you wear this belt.", 1),
  magicItem("Staff of the Magi", "Staff", "Legendary", "by a spellcaster", "Absorb spells and command a vast arsenal of powerful magic.", 4),
  magicItem("Robe of the Archmagi", "Wondrous Item", "Legendary", "by a spellcaster", "Set your unarmored AC, gain advantage on saves against magic, and raise your spell save DC.", 2),
  magicItem("Cloak of Invisibility", "Wondrous Item", "Legendary", true, "Become invisible at will while the hood is raised.", 1),
  magicItem("Rod of Lordly Might", "Rod", "Legendary", true, "A shifting weapon-rod with six magical functions at your command.", 4),
  magicItem("Ring of Djinni Summoning", "Ring", "Legendary", true, "Summon a djinni to serve and fight for you once per day.", 0),
  magicItem("Ring of Three Wishes", "Ring", "Legendary", false, "Holds up to three charges, each casting the Wish spell.", 0),
  magicItem("Ioun Stone of Mastery", "Wondrous Item", "Legendary", true, "A stone that orbits your head and raises your proficiency bonus by 1.", 0),
  magicItem("Scarab of Protection", "Wondrous Item", "Legendary", true, "Advantage on saves against spells and a ward against several deadly effects.", 0),
  magicItem("Deck of Many Things", "Wondrous Item", "Artifact", false, "Draw cards to gain wild boons or suffer catastrophic curses.", 1),
  magicItem("Talisman of Pure Good", "Wondrous Item", "Artifact", "by a creature of good alignment", "Empowers holy magic and can cast evil creatures into a fiery pit.", 1),
  // ── Expanded Armor ──
  magicItem("Adamantine Armor", "Armor (medium or heavy)", "Uncommon", false, "Critical hits against you become normal hits while you wear it.", 40),
  magicItem("Mithral Armor", "Armor (medium or heavy)", "Uncommon", false, "Lightweight: no Stealth disadvantage and it ignores its Strength requirement.", 20),
  magicItem("Mariner's Armor", "Armor (light, medium, or heavy)", "Uncommon", false, "Gain a swimming speed and you cannot drown while wearing it.", 20),
  magicItem("Elven Chain", "Armor (chain shirt)", "Rare", false, "Counts as light armor, grants +1 AC, and you are proficient even without training.", 20),
  magicItem("Glamoured Studded Leather", "Armor (studded leather)", "Rare", false, "+1 AC and, as a bonus action, disguise it as any set of clothing.", 13),
  magicItem("Dragon Scale Mail", "Armor (scale mail)", "Very Rare", true, "+1 AC, resistance to one damage type, and advantage against a dragon's frightful presence.", 45),
  magicItem("Armor of Resistance", "Armor (light, medium, or heavy)", "Rare", true, "Grants resistance to one damage type chosen when the armor is made.", 40),
  magicItem("Dwarven Plate", "Armor (plate)", "Very Rare", false, "+2 AC and resistance to being shoved or knocked prone.", 65),
  magicItem("Plate Armor of Etherealness", "Armor (plate)", "Legendary", true, "Once per day, slip into the Ethereal Plane for up to 10 minutes.", 65),
  magicItem("Armor, +3", "Armor (any)", "Legendary", false, "+3 bonus to AC while you wear this armor.", 20),
  // ── Expanded Weapons ──
  magicItem("Moon-Touched Sword", "Weapon (any sword)", "Common", false, "In darkness the blade glows, shedding soft moonlight around you.", 3),
  magicItem("Sun Blade", "Weapon (longsword)", "Rare", true, "A blade of pure sunlight dealing radiant damage, extra against undead, and shedding daylight.", 3),
  magicItem("Sword of Wounding", "Weapon (any sword)", "Rare", true, "Hits open lasting wounds that keep bleeding for ongoing damage.", 3),
  magicItem("Sword of Life Stealing", "Weapon (any sword)", "Rare", true, "On a solid hit, drain extra necrotic damage and gain temporary hit points.", 3),
  magicItem("Sword of Vengeance", "Weapon (any sword)", "Uncommon", true, "+1 sword bound to a vengeful spirit that resists your control.", 3),
  magicItem("Dragon Slayer", "Weapon (any sword)", "Rare", false, "+1 sword that deals extra damage to dragons and dragon-kin.", 3),
  magicItem("Giant Slayer", "Weapon (any axe or sword)", "Rare", false, "+1 weapon that deals extra damage to giants and can knock them prone.", 4),
  magicItem("Vicious Weapon", "Weapon (any)", "Rare", false, "On a natural 20, the weapon deals an extra 2d6 damage of its type.", 3),
  magicItem("Berserker Axe", "Weapon (any axe)", "Rare", true, "+1 axe that raises your maximum hit points but risks an uncontrolled rage.", 4),
  magicItem("Bloodrage Greataxe", "Weapon (greataxe)", "Rare", true, "A rune-etched +1 greataxe that drinks the blood it spills: every hit deals an extra 1d6 necrotic damage. While you are below half your hit points the runes blaze — you deal an additional 1d6 necrotic (2d6 total) and have advantage on Strength checks made to shove or grapple. When you reduce a creature to 0 hit points with it, you gain temporary hit points equal to your proficiency bonus as the axe feeds on the kill.", 7),
  magicItem("Trident of Fish Command", "Weapon (trident)", "Uncommon", true, "Expend a charge to dominate creatures that breathe water.", 4),
  magicItem("Javelin of Lightning", "Weapon (javelin)", "Uncommon", false, "Hurl it to streak forward as a bolt of lightning that bursts on impact.", 2),
  magicItem("Mace of Smiting", "Weapon (mace)", "Rare", false, "+1 mace with extra force against constructs, which it can shatter outright.", 4),
  magicItem("Mace of Terror", "Weapon (mace)", "Rare", true, "Expend a charge to radiate fear, sending nearby foes fleeing.", 4),
  magicItem("Scimitar of Speed", "Weapon (scimitar)", "Very Rare", true, "+2 scimitar that grants an extra attack as a bonus action each turn.", 3),
  magicItem("Hammer of Thunderbolts", "Weapon (maul)", "Legendary", false, "A giant-slaying maul that booms on a hit and can stun with a thrown blow.", 15),
  magicItem("Sword of Answering", "Weapon (longsword)", "Legendary", true, "+3 sword that lets you riposte the instant a foe strikes you.", 3),
  // ── Expanded Rings ──
  magicItem("Ring of Water Walking", "Ring", "Uncommon", false, "Stand and move across any liquid as though it were solid ground.", 0),
  magicItem("Ring of Swimming", "Ring", "Uncommon", false, "Gain a swimming speed of 40 feet while wearing it.", 0),
  magicItem("Ring of Warmth", "Ring", "Uncommon", true, "Resistance to cold damage and comfort in freezing weather.", 0),
  magicItem("Ring of Feather Falling", "Ring", "Rare", true, "You never take falling damage and always land on your feet.", 0),
  magicItem("Ring of the Ram", "Ring", "Rare", true, "Expend charges to slam a target with a forceful ram of force.", 0),
  magicItem("Ring of Evasion", "Ring", "Rare", true, "Expend a charge to automatically succeed on a Dexterity saving throw.", 0),
  magicItem("Ring of X-ray Vision", "Ring", "Rare", true, "See through solid matter for a short time, straining your body.", 0),
  magicItem("Ring of Shooting Stars", "Ring", "Very Rare", true, "Call sparks, ball lightning, and shooting stars in dim light or darkness.", 0),
  magicItem("Ring of Spell Turning", "Ring", "Legendary", true, "Reflect single-target spells back at the caster who targets you.", 0),
  magicItem("Ring of Invisibility", "Ring", "Legendary", true, "Turn invisible at will as an action.", 0),
  magicItem("Ring of Elemental Command", "Ring", "Legendary", true, "Command elementals and grow in power as you bond with the ring.", 0),
  // ── Expanded Wands ──
  magicItem("Wand of Secrets", "Wand", "Uncommon", false, "Point the wand to reveal a nearby hidden door or trap.", 1),
  magicItem("Wand of Magic Detection", "Wand", "Uncommon", false, "Cast Detect Magic using the wand's charges.", 1),
  magicItem("Wand of Web", "Wand", "Uncommon", "by a spellcaster", "Cast Web from the wand using its charges.", 1),
  magicItem("Wand of Wonder", "Wand", "Rare", "by a spellcaster", "Unleash a wildly unpredictable magical effect each time.", 1),
  magicItem("Wand of Binding", "Wand", "Rare", "by a spellcaster", "Cast Hold Monster or Hold Person and resist paralysis and restraint.", 1),
  magicItem("Wand of Paralysis", "Wand", "Rare", "by a spellcaster", "Force a creature to be paralyzed on a failed save.", 1),
  magicItem("Wand of Fear", "Wand", "Rare", "by a spellcaster", "Frighten a group of creatures or drive one to flee.", 1),
  magicItem("Wand of Enemy Detection", "Wand", "Rare", true, "Sense hostile creatures nearby, even hidden ones.", 1),
  magicItem("Wand of Pyrotechnics", "Wand", "Common", false, "Conjure harmless sparks, fireworks, and puffs of colored smoke.", 1),
  // ── Expanded Rods & Staffs ──
  magicItem("Rod of the Pact Keeper, +1", "Rod", "Uncommon", "by a warlock", "+1 to warlock spell attacks and save DC, and regain a spell slot once per day.", 2),
  magicItem("Rod of Rulership", "Rod", "Rare", true, "Command nearby creatures to obey you for a short time.", 2),
  magicItem("Rod of Alertness", "Rod", "Very Rare", true, "+1 to initiative and Perception, cast detection spells, and shield allies.", 2),
  magicItem("Rod of Security", "Rod", "Very Rare", false, "Retreat with your allies into a safe extradimensional paradise.", 2),
  magicItem("Staff of Healing", "Staff", "Rare", "by a bard, cleric, or druid", "Cast Cure Wounds, Lesser Restoration, and Mass Cure Wounds.", 4),
  magicItem("Staff of the Woodlands", "Staff", "Rare", "by a druid", "+2 to druid spells, nature magic, and the power to shape and animate trees.", 4),
  magicItem("Staff of Withering", "Staff", "Rare", "by a cleric, druid, or warlock", "Deal necrotic damage and sap a target's Strength or Constitution.", 4),
  magicItem("Staff of Frost", "Staff", "Very Rare", "by a spellcaster", "Cast cold spells from the staff and gain resistance to cold.", 4),
  magicItem("Staff of Striking", "Staff", "Very Rare", true, "A +3 quarterstaff that can expend charges for heavy force damage.", 4),
  magicItem("Staff of Thunder and Lightning", "Staff", "Very Rare", true, "A +2 staff with several thunder and lightning attack functions.", 4),
  // ── Expanded Wondrous Items ──
  magicItem("Cloak of Many Fashions", "Wondrous Item", "Common", false, "Change the cloak's color, pattern, and cut with a thought.", 1),
  magicItem("Bead of Nourishment", "Wondrous Item", "Common", false, "A flavorless bead that nourishes you like a full day of food and water.", 0),
  magicItem("Perfume of Bewitching", "Wondrous Item", "Common", false, "Apply the scent to gain brief advantage on Charisma checks.", 0),
  magicItem("Instrument of Illusions", "Wondrous Item", "Common", false, "Your music conjures harmless illusions that dance in time with it.", 1),
  magicItem("Pole of Angling", "Wondrous Item", "Common", false, "Command a plain pole to become a fishing rod, tackle included.", 2),
  magicItem("Rope of Mending", "Wondrous Item", "Common", false, "Cut the rope apart, then command the pieces to fuse back together.", 3),
  magicItem("Orb of Direction", "Wondrous Item", "Common", false, "As an action, learn which way is north.", 1),
  magicItem("Talking Doll", "Wondrous Item", "Common", false, "A doll that speaks a set of phrases you record into it.", 1),
  magicItem("Heward's Handy Spice Pouch", "Wondrous Item", "Common", false, "Reach in to draw a pinch of whatever cooking spice you name.", 1),
  magicItem("Dread Helm", "Wondrous Item", "Common", false, "A fearsome helm that makes your eyes glow red in shadow.", 3),
  magicItem("Ersatz Eye", "Wondrous Item", "Common", true, "A replacement eye that lets you see normally and never leaves its socket.", 0),
  magicItem("Stone of Good Luck", "Wondrous Item", "Uncommon", true, "+1 bonus to ability checks and saving throws while carried.", 0),
  magicItem("Pearl of Power", "Wondrous Item", "Uncommon", "by a spellcaster", "Once per day, recover one expended spell slot of 3rd level or lower.", 0),
  magicItem("Amulet of Proof against Detection and Location", "Wondrous Item", "Uncommon", true, "You can't be targeted or found by divination magic.", 0),
  magicItem("Brooch of Shielding", "Wondrous Item", "Uncommon", true, "Resistance to force damage and immunity to the Magic Missile spell.", 0),
  magicItem("Broom of Flying", "Wondrous Item", "Uncommon", false, "A flying broom that carries you or speeds to you on command.", 3),
  magicItem("Boots of the Winterlands", "Wondrous Item", "Uncommon", true, "Resistance to cold, easy travel over ice, and comfort in frozen climes.", 1),
  magicItem("Cap of Water Breathing", "Wondrous Item", "Uncommon", false, "Breathe normally while submerged underwater.", 0),
  magicItem("Cloak of the Manta Ray", "Wondrous Item", "Uncommon", false, "Breathe water and gain a swimming speed while the hood is up.", 1),
  magicItem("Decanter of Endless Water", "Wondrous Item", "Uncommon", false, "Pour out a stream, fountain, or geyser of fresh or salt water.", 2),
  magicItem("Deck of Illusions", "Wondrous Item", "Uncommon", false, "Play a card to conjure an illusory creature until it is dismissed.", 0.5),
  magicItem("Dust of Disappearance", "Wondrous Item", "Uncommon", false, "Throw the dust to turn yourself and nearby creatures invisible.", 0),
  magicItem("Efficient Quiver", "Wondrous Item", "Uncommon", false, "A quiver with three compartments, each holding far more than it should.", 2),
  magicItem("Eversmoking Bottle", "Wondrous Item", "Uncommon", false, "Release a billowing cloud of thick smoke on command.", 1),
  magicItem("Eyes of Charming", "Wondrous Item", "Uncommon", true, "Meet a creature's gaze to cast Charm Person on it.", 0),
  magicItem("Eyes of Minute Seeing", "Wondrous Item", "Uncommon", false, "See fine detail and spot hidden things with uncanny acuity.", 0),
  magicItem("Gem of Brightness", "Wondrous Item", "Uncommon", false, "Expend charges to shed light or blind a creature with a brilliant flash.", 1),
  magicItem("Gloves of Missile Snaring", "Wondrous Item", "Uncommon", true, "Catch or deflect a ranged weapon attack that hits you.", 0),
  magicItem("Gloves of Swimming and Climbing", "Wondrous Item", "Uncommon", true, "Gain a climbing and swimming speed and a firmer grip.", 0),
  magicItem("Gloves of Thievery", "Wondrous Item", "Uncommon", false, "+5 bonus to lockpicking and sleight of hand while worn.", 0),
  magicItem("Hat of Disguise", "Wondrous Item", "Uncommon", true, "Cast Disguise Self at will to change your appearance.", 0),
  magicItem("Helm of Comprehending Languages", "Wondrous Item", "Uncommon", false, "Understand any spoken language and read any writing.", 3),
  magicItem("Lantern of Revealing", "Wondrous Item", "Uncommon", false, "Its light reveals invisible creatures and objects nearby.", 2),
  magicItem("Medallion of Thoughts", "Wondrous Item", "Uncommon", true, "Read the surface thoughts of a nearby creature.", 0),
  magicItem("Necklace of Adaptation", "Wondrous Item", "Uncommon", true, "Breathe normally in any environment and resist harmful gases.", 0),
  magicItem("Periapt of Health", "Wondrous Item", "Uncommon", false, "You are immune to disease while wearing it.", 0),
  magicItem("Pipes of the Sewers", "Wondrous Item", "Uncommon", true, "Summon and command swarms of rats with your piping.", 2),
  magicItem("Restorative Ointment", "Wondrous Item", "Uncommon", false, "A jar of salve that heals wounds or neutralizes poison.", 0.5),
  magicItem("Robe of Useful Items", "Wondrous Item", "Uncommon", false, "Tear off a patch to produce a handy mundane or magical object.", 1),
  magicItem("Rope of Climbing", "Wondrous Item", "Uncommon", false, "A 60-foot rope that moves, knots, and anchors itself on command.", 3),
  magicItem("Wind Fan", "Wondrous Item", "Uncommon", false, "Wave the fan to conjure a strong gust of wind.", 0),
  magicItem("Belt of Hill Giant Strength", "Wondrous Item", "Rare", true, "Your Strength score becomes 21 while you wear this belt.", 1),
  magicItem("Belt of Stone Giant Strength", "Wondrous Item", "Very Rare", true, "Your Strength score becomes 23 while you wear this belt.", 1),
  magicItem("Belt of Frost Giant Strength", "Wondrous Item", "Very Rare", true, "Your Strength score becomes 23 while you wear this belt.", 1),
  magicItem("Belt of Fire Giant Strength", "Wondrous Item", "Very Rare", true, "Your Strength score becomes 25 while you wear this belt.", 1),
  magicItem("Belt of Cloud Giant Strength", "Wondrous Item", "Legendary", true, "Your Strength score becomes 27 while you wear this belt.", 1),
  magicItem("Belt of Dwarvenkind", "Wondrous Item", "Rare", true, "Boost your Constitution, resist poison, and speak and understand Dwarvish.", 1),
  magicItem("Bag of Beans", "Wondrous Item", "Rare", false, "Plant a magic bean to sprout a random wonder or hazard.", 0.5),
  magicItem("Figurine of Wondrous Power (Bronze Griffon)", "Wondrous Item", "Rare", false, "Toss the figurine to summon a loyal griffon steed for a time.", 0.5),
  magicItem("Folding Boat", "Wondrous Item", "Rare", false, "A small box that unfolds into a rowboat or a full sailing ship.", 4),
  magicItem("Handy Haversack", "Wondrous Item", "Rare", false, "A backpack of bottomless side pouches you can reach into instantly.", 5),
  magicItem("Helm of Teleportation", "Wondrous Item", "Rare", true, "Expend a charge to cast the Teleport spell.", 3),
  magicItem("Horn of Blasting", "Wondrous Item", "Rare", false, "Sound the horn to unleash a devastating cone of thunderous force.", 2),
  magicItem("Horseshoes of Speed", "Wondrous Item", "Rare", false, "A mount shod with these gains a great boost to its speed.", 4),
  magicItem("Instant Fortress", "Wondrous Item", "Rare", false, "Toss an iron cube that grows into a small defensive tower on command.", 10),
  magicItem("Ioun Stone of Protection", "Wondrous Item", "Rare", true, "A stone that orbits your head and grants +1 AC.", 0),
  magicItem("Mantle of Spell Resistance", "Wondrous Item", "Rare", true, "Advantage on saving throws against spells while worn.", 1),
  magicItem("Necklace of Fireballs", "Wondrous Item", "Rare", false, "Pluck a bead and hurl it to detonate as a fireball.", 0),
  magicItem("Periapt of Proof against Poison", "Wondrous Item", "Rare", true, "Immunity to poison damage and the poisoned condition.", 0),
  magicItem("Portable Hole", "Wondrous Item", "Rare", false, "Unfold a cloth into a 10-foot-deep extradimensional pit.", 0),
  magicItem("Robe of Eyes", "Wondrous Item", "Rare", true, "See in every direction with darkvision and truesight, but light spells blind you.", 1),
  magicItem("Rope of Entanglement", "Wondrous Item", "Rare", false, "Command the rope to lash out and entangle a creature.", 3),
  magicItem("Wings of Flying", "Wondrous Item", "Rare", true, "A cloak that becomes leathery or feathered wings, granting flight for a time.", 1),
  magicItem("Amulet of the Planes", "Wondrous Item", "Very Rare", true, "Cast Plane Shift to travel to other planes of existence.", 0),
  magicItem("Robe of Stars", "Wondrous Item", "Very Rare", true, "Store spells in its stars, walk the Astral Plane, and bolster your saves.", 1),
  magicItem("Well of Many Worlds", "Wondrous Item", "Legendary", false, "Unfold a cloth to open a portal to another world or plane.", 0),
  magicItem("Apparatus of Kwalish", "Wondrous Item", "Legendary", false, "Climb inside an iron crab-shaped vehicle that can walk and swim.", 0),
  magicItem("Cubic Gate", "Wondrous Item", "Legendary", false, "A cube whose faces open gates to six different planes of existence.", 0),
  magicItem("Iron Flask", "Wondrous Item", "Legendary", false, "Trap a creature inside the flask, then release it to serve you once.", 1),
  magicItem("Ioun Stone of Regeneration", "Wondrous Item", "Legendary", true, "A stone that heals you steadily while it orbits your head.", 0),
  // ── Expanded Potions ──
  magicItem("Potion of Growth", "Potion", "Uncommon", false, "Grow one size larger for a short time, increasing your strength and reach.", 0.5),
  magicItem("Potion of Resistance", "Potion", "Uncommon", false, "Resistance to one chosen damage type for 1 hour.", 0.5),
  magicItem("Potion of Animal Friendship", "Potion", "Uncommon", false, "Cast Animal Friendship at will for 1 hour after drinking it.", 0.5),
  magicItem("Potion of Diminution", "Potion", "Rare", false, "Shrink one size smaller for a short time.", 0.5),
  magicItem("Potion of Gaseous Form", "Potion", "Rare", false, "Become a cloud of mist for up to 1 hour.", 0.5),
  magicItem("Potion of Clairvoyance", "Potion", "Rare", false, "Gain the effect of the Clairvoyance spell.", 0.5),
  magicItem("Potion of Mind Reading", "Potion", "Rare", false, "Gain the effect of the Detect Thoughts spell.", 0.5),
  magicItem("Potion of Giant Strength (Hill)", "Potion", "Uncommon", false, "Your Strength score becomes 21 for 1 hour.", 0.5),
  magicItem("Potion of Giant Strength (Frost)", "Potion", "Rare", false, "Your Strength score becomes 23 for 1 hour.", 0.5),
  magicItem("Potion of Giant Strength (Fire)", "Potion", "Rare", false, "Your Strength score becomes 25 for 1 hour.", 0.5),
  magicItem("Potion of Giant Strength (Cloud)", "Potion", "Very Rare", false, "Your Strength score becomes 27 for 1 hour.", 0.5),
  magicItem("Potion of Giant Strength (Storm)", "Potion", "Legendary", false, "Your Strength score becomes 29 for 1 hour.", 0.5),
  // ── Expanded spellcasting focuses ──
  magicItem("Amulet of the Devout, +1", "Wondrous Item", "Uncommon", "by a cleric or paladin", "+1 to spell attacks and save DC, and extra fuel for your Channel Divinity.", 1),
  magicItem("Bloodwell Vial, +1", "Wondrous Item", "Uncommon", "by a sorcerer", "+1 to spell attacks and save DC, store sorcery points, and recover them.", 1),
  magicItem("Arcane Grimoire, +1", "Wondrous Item", "Uncommon", "by a wizard", "+1 to spell attacks and save DC, with a spare use of Arcane Recovery.", 3),
  magicItem("Rhythm-Maker's Drum, +1", "Wondrous Item", "Uncommon", "by a bard", "+1 to spell attacks and save DC, and a boost to your Bardic Inspiration.", 3),
  magicItem("Moon Sickle, +1", "Weapon (sickle)", "Uncommon", "by a druid or ranger", "+1 weapon and spell bonus that also strengthens your healing spells.", 2),
  magicItem("All-Purpose Tool, +1", "Wondrous Item", "Uncommon", "by an artificer", "A +1 spellcasting focus that can mimic any set of artisan's tools.", 2)
];

const LEVEL_CHOICE_RULES = {
  2014: {
    Bard: { expertise: { 3: 2, 10: 2 } },
    Rogue: { expertise: { 1: 2, 6: 2 } },
    Sorcerer: { metamagic: { 3: 2, 10: 1, 17: 1 } },
    Warlock: { invocations: { 2: 2, 5: 1, 7: 1, 9: 1, 12: 1, 15: 1, 18: 1 } }
  },
  2024: {
    Bard: { expertise: { 2: 2, 9: 2 } },
    Ranger: { expertise: { 9: 2 } },
    Rogue: { expertise: { 1: 2, 6: 2 } },
    Sorcerer: { metamagic: { 2: 2, 10: 2, 17: 2 } },
    Warlock: { invocations: { 1: 1, 2: 2, 5: 2, 7: 1, 9: 1, 12: 1, 15: 1, 18: 1 } }
  }
};

const CANTRIP_PROGRESSION = {
  2014: {
    Bard: { 4: 1, 10: 1 }, Cleric: { 4: 1, 10: 1 }, Druid: { 4: 1, 10: 1 },
    Sorcerer: { 4: 1, 10: 1 }, Warlock: { 4: 1, 10: 1 }, Wizard: { 4: 1, 10: 1 }
  },
  2024: {
    Bard: { 4: 1, 10: 1 }, Cleric: { 4: 1, 10: 1 }, Druid: { 4: 1, 10: 1 },
    Sorcerer: { 4: 1, 10: 1 }, Warlock: { 4: 1, 10: 1 }, Wizard: { 4: 1, 10: 1 }
  }
};

const SPELL_PROGRESSION = {
  2014: {
    Bard: { mode: "known", totals: [4,5,6,7,8,9,10,11,12,14,15,15,16,18,19,19,20,22,22,22] },
    Ranger: { mode: "known", totals: [0,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11] },
    Sorcerer: { mode: "known", totals: [2,3,4,5,6,7,8,9,10,11,12,12,13,13,14,14,15,15,15,15] },
    Warlock: { mode: "known", totals: [2,3,4,5,6,7,8,9,10,10,11,11,12,12,13,13,14,14,15,15] },
    Wizard: { mode: "spellbook", perLevel: 2 }
  },
  2024: {
    Bard: { mode: "prepared", totals: [4,5,6,7,9,10,11,12,14,15,16,16,17,17,18,18,19,20,21,22] },
    Cleric: { mode: "prepared", totals: [4,5,6,7,9,10,11,12,14,15,16,16,17,17,18,18,19,20,21,22] },
    Druid: { mode: "prepared", totals: [4,5,6,7,9,10,11,12,14,15,16,16,17,17,18,18,19,20,21,22] },
    Paladin: { mode: "prepared", totals: [2,3,4,5,6,6,7,7,9,9,10,10,11,11,12,12,14,14,15,15] },
    Ranger: { mode: "prepared", totals: [2,3,4,5,6,6,7,7,9,9,10,10,11,11,12,12,14,14,15,15] },
    Sorcerer: { mode: "prepared", totals: [2,4,6,7,9,10,11,12,14,15,16,16,17,17,18,18,19,20,21,22] },
    Warlock: { mode: "prepared", totals: [2,3,4,5,6,7,8,9,10,10,11,11,12,12,13,13,14,14,15,15] },
    Wizard: { mode: "spellbook", perLevel: 2 }
  }
};

if (typeof module !== "undefined") {
  module.exports = { FEATS, CLASS_FEATURES, SUBCLASS_FEATURES, PROGRESSION_OPTIONS, LEVEL_CHOICE_RULES, CANTRIP_PROGRESSION, SPELL_PROGRESSION };
}
